sudo: false
language: scala
scala:
  - 2.12.2
jdk:
  - openjdk8
before_install:
  - source .env
install:
  - curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/"${MILL_VERSION}"/"${MILL_VERSION}" && chmod +x ~/bin/mill
  - export PATH=~/bin/mill:$PATH
before_script:
  - travis_retry mill clean
  - mill --disable-ticker -s _.compile
script:
  - mill --disable-ticker -s _.test
  - mill --disable-ticker -s _.localJar
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
cache:
  directories:
    - $HOME/.ivy2/cache
